### ISSUE TITLE
Are playids in ascending order by time?

### ISSUE THREAD

**Issue by alexk307** [nfl-football-ops/Big-Data-Bowl#1]
In the schema.md:

```
playId: Play identifier, not unique across games (numeric)
```

Are these `playid`s in ascending order by time. For example: for a given game, is it always true that playid=x happened before playid=x+1? If playid1 > playid2, does that guarantee that playid1 happened after playid2?

**Comment by nfl-football-ops** [comment]
Correct! 

`playId`'s are ascending, beginning with the first play of the game. *Note*: you can also use time and quarter to assess time.

**Comment by alexk307** [comment]
Thanks for the quick response!
